name: 04 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4
            - name: Printing folders
              run: ls -al 
        